// init list and big photo
export const INIT_SHOW_BIGPHOTO = 'INIT_SHOW_BIGPHOTO';
export const INIT_THUMBNAIL_START = 'INIT_THUMBNAIL_START';
export const INIT_THUMBNAIL_LIST = 'INIT_THUMBNAIL_LIST';
export const INIT_ACTIVE_PHOTO = 'INIT_ACTIVE_PHOTO';

export const FETCH_PHOTO_LIST_FAILED = 'FETCH_PHOTO_LIST_FAILED';

// modal
export const MODAL_SHOW = 'MODAL_SHOW';
export const MODAL_CLOSE = 'MODAL_CLOSE';
export const MODAL_REMOVE_SINGLE_PHOTO = 'MODAL_REMOVE_SINGLE_PHOTO';
export const MODAL_SEND = 'MODAL_SEND';

// 
export const PHOTO_INCREMENT = 'PHOTO_INCREMENT';
export const PHOTO_DECREMENT = 'PHOTO_DECREMENT';